"""work table

Revision ID: 017cbf4d2f50
Revises: a2c4845491cb
Create Date: 2023-03-25 09:12:09.757947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '017cbf4d2f50'
down_revision = 'a2c4845491cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre', sa.Enum('default', 'fiction', 'nonfiction', 'poetry', 'drama', name='genre'), nullable=True),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('body', sa.String(length=8000), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('prompter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prompter_id'], ['prompter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_timestamp'))

    op.drop_table('work')
    # ### end Alembic commands ###
