"""prompter table

Revision ID: a2c4845491cb
Revises: 
Create Date: 2023-03-25 09:03:53.040292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2c4845491cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompter', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompter_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_prompter_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompter', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompter_username'))
        batch_op.drop_index(batch_op.f('ix_prompter_email'))

    op.drop_table('prompter')
    # ### end Alembic commands ###
