"""Remove unnecessary email field

Revision ID: ce8fe100475f
Revises: 76db8b7ccb5b
Create Date: 2023-03-25 14:05:45.806688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce8fe100475f'
down_revision = '76db8b7ccb5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompter', schema=None) as batch_op:
        batch_op.drop_index('ix_prompter_email')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.create_index('ix_prompter_email', ['email'], unique=False)

    # ### end Alembic commands ###
