"""followers and likers

Revision ID: ebd3cc35030e
Revises: ce8fe100475f
Create Date: 2023-03-25 14:29:02.359998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebd3cc35030e'
down_revision = 'ce8fe100475f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follower',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['prompter.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['prompter.id'], )
    )
    op.create_table('liker',
    sa.Column('liker_id', sa.Integer(), nullable=True),
    sa.Column('liked_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['liked_id'], ['work.id'], ),
    sa.ForeignKeyConstraint(['liker_id'], ['prompter.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('liker')
    op.drop_table('follower')
    # ### end Alembic commands ###
